[package]
name = "cfs-sys"
description = "Low-level bindings to cFE and OSAL C APIs"
version = "0.1.0"
authors = ["Zachary Catlin <zec0@psu.edu>"]
edition = "2018"
readme = "README.md"
publish = false

[dependencies]
libc = { version = "^0.2.107", default-features = false }

[build-dependencies]
bindgen = "^0.59.1"
