[package]
name = "cfs"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfs-sys = { git = "https://git.psu.edu/zec0/cfs-sys-rs.git", rev = "aa0197b2bce9ab1405b5ab4c62844a0665f3b1a3" }
