[package]
name = "cfs"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfs-sys = { git = "https://git.psu.edu/zec0/cfs-sys-rs.git", rev = "d97258adee8f790bf19fbdb5d4362608e98afe81" }
printf-wrap = { git = "https://git.psu.edu/zec0/printf-wrap.git", rev = "4c7f9dfa3906884586c87044259cb6b8e8393543", default-features = false }
libc = { version = "^0.2.107", default-features = false }
