[package]
name = "cfs"
version = "0.0.0"
edition = "2021"
publish = false
workspace = ".."

[dependencies]
cfs-sys = { path = "../cfs-sys" }
printf-wrap = { version = "^0.1", default-features = false }
libc = { version = "^0.2.107", default-features = false }
