// TODO: add doc comment

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(improper_ctypes)]

pub type char = ::std::os::raw::c_char;

// ${OUT_DIR}/cfs-all.rs is generated by the build script
include!(concat!(env!("OUT_DIR"), "/cfs-all.rs"));
