// TODO: add doc comment

//#![no_std]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(improper_ctypes)]

// ${OUT_DIR}/cfs-all.rs is generated by the build script
include!(concat!(env!("OUT_DIR"), "/cfs-all.rs"));

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
