// Copyright (c) 2021-2023 The Pennsylvania State University and the project contributors.
// SPDX-License-Identifier: Apache-2.0

//! Low-level, `unsafe` bindings to the C APIs of [cFE](https://github.com/nasa/cFE)
//! and [OSAL](https://github.com/nasa/osal).
//!
//! This is `n2o4`'s equivalent of a
//! [`*-sys` crate](https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages)
//! for the cFE and OSAL APIs.
//! Generally, users of `n2o4` will not use this module directly,
//! preferring the safe wrappers provided in the rest of `n2o4`.
//! However, this module is available
//! if one needs to use something for which safe wrappers haven't been made.
//!
//! The definitions in this module are auto-generated by
//! [bindgen](https://github.com/rust-lang/rust-bindgen),
//! so there's no Rustdoc comments available.
//! Check out the
//! [cFE user's guide](https://github.com/nasa/cFE/blob/gh-pages/cfe-usersguide.pdf)
//! for details about types and functions.
//!
//! Those identifiers starting with `S_`, `X_`, and `SHIM_` are the result
//! of hand-written C code required to make `bindgen` create bindings for
//! certain constants and function; each is the same as the C constant
//! or function without the prefix in its name.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(improper_ctypes)]
#![allow(missing_docs)]
#![allow(unused)]

pub type char = ::core::ffi::c_char;

// ${OUT_DIR}/cfs-all.rs is generated by the build script
include!(concat!(env!("OUT_DIR"), "/cfs-all.rs"));
